/**
 * @file Gadget.hpp
 * @brief Gadget domain model. Generated by scripts/new-resource.sh.
 *
 * Add your real columns below — keep the struct, from_row() and to_json()
 * in sync (each field appears in all three). Never serialize secrets in
 * to_json (see tests/unit/test_domain_serialization.cpp).
 */

#pragma once

#include <pqxx/pqxx>
#include <string>

#include <nlohmann/json.hpp>

namespace Domain {

struct Gadget {
    std::string id;    // UUID v4 (text)
    std::string name;  // TODO: replace with your real columns
    std::string created_at;

    template <typename Row>
    static Gadget from_row(const Row& row) {
        Gadget e;
        e.id = row["id"].template as<std::string>();
        e.name = row["name"].template as<std::string>();
        e.created_at = row["created_at"].template as<std::string>();
        return e;
    }
};

inline void to_json(nlohmann::json& j, const Gadget& e) {
    j = nlohmann::json{
        {"id", e.id},
        {"name", e.name},
        {"created_at", e.created_at},
    };
}

}  // namespace Domain
