/**
 * @file GadgetsController.hpp
 * @brief Gadget CRUD endpoints. Generated by scripts/new-resource.sh.
 *        Admin-gated; follows docs/CONVENTIONS.md.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

#include "api/Guards.hpp"
#include "api/HandlerSupport.hpp"
#include "api/RequestUtils.hpp"
#include "api/Validation.hpp"
#include "domain/Gadget.hpp"
#include "repositories/GadgetRepository.hpp"
#include "utils/ErrorResponse.hpp"

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class GadgetsController : public HttpController<GadgetsController> {
public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(GadgetsController::listGadgets, "/api/v1/gadgets", Get);
    ADD_METHOD_TO(GadgetsController::createGadget, "/api/v1/gadgets", Post);
    ADD_METHOD_TO(GadgetsController::getGadget, "/api/v1/gadgets/{1}", Get);
    ADD_METHOD_TO(GadgetsController::deleteGadget, "/api/v1/gadgets/{1}", Delete);
    METHOD_LIST_END

    void listGadgets(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        const auto page = parse_page_params(req, /*default_limit=*/50, /*max_limit=*/200);
        with_repo_errors(callback, "listGadgets", [&] {
            Repositories::GadgetRepository repo;
            auto items = repo.list(page.limit, page.offset);
            long total = repo.count();
            callback(Response::paginated(to_json_array(items), total, page.limit, page.offset));
        });
    }

    void createGadget(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        json body;
        if (!Validation::parse_body(req, body, callback))
            return;
        Validation::Errors errs;
        Validation::require(errs, body, "name");
        Validation::string_length(errs, body, "name", 1, 255);
        if (errs.any()) {
            callback(Validation::response_400(errs));
            return;
        }
        with_repo_errors(callback, "createGadget", [&] {
            Repositories::GadgetRepository repo;
            auto created = repo.create(body["name"].get<std::string>());
            callback(Response::created({{"data", json(created)}}));
        });
    }

    void getGadget(const HttpRequestPtr& req,
                   std::function<void(const HttpResponsePtr&)>&& callback,
                   const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!require_valid_uuid(id, callback))
            return;
        with_repo_errors(callback, "getGadget", [&] {
            Repositories::GadgetRepository repo;
            auto found = repo.find(id);
            if (!found) {
                callback(ErrorResponse::not_found("gadget"));
                return;
            }
            callback(Response::ok({{"data", json(*found)}}));
        });
    }

    void deleteGadget(const HttpRequestPtr& req,
                      std::function<void(const HttpResponsePtr&)>&& callback,
                      const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!require_valid_uuid(id, callback))
            return;
        with_repo_errors(callback, "deleteGadget", [&] {
            Repositories::GadgetRepository repo;
            repo.remove(id);
            callback(Response::ok({{"message", "Gadget deleted"}}));
        });
    }
};

}  // namespace Api
