/**
 * @file GadgetRepository.hpp
 * @brief All SQL touching `gadgets` lives here. Generated by
 *        scripts/new-resource.sh. Controllers never touch pqxx directly.
 */

#pragma once

#include <optional>
#include <pqxx/pqxx>
#include <string>
#include <vector>

#include "database/Database.hpp"
#include "domain/Gadget.hpp"
#include "repositories/CrudBase.hpp"
#include "repositories/RepoErrors.hpp"
#include "repositories/SqlErrors.hpp"

namespace Repositories {

// Derive from the generic repo bases so Api::with_repo_errors maps them to
// 409 / 404 instead of a bare 500 (see RepoErrors.hpp / HandlerSupport.hpp).
struct DuplicateGadget : ConflictError {
    DuplicateGadget() : ConflictError("gadget_exists", "a gadget with that name already exists") {}
};

struct GadgetNotFound : NotFoundError {
    GadgetNotFound() : NotFoundError("gadget") {}
};

class GadgetRepository : public CrudBase<GadgetRepository, Domain::Gadget, std::string> {
public:
    // CrudBase supplies find(id) / list(limit, offset) / count() from these
    // four constants — only the bespoke writes below are hand-written.
    static constexpr const char* kTable = "gadgets";
    static constexpr const char* kColumns = "id, name, created_at";
    static constexpr const char* kIdColumn = "id";
    static constexpr const char* kOrderBy = "created_at DESC";

    Domain::Gadget create(const std::string& name) {
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("INSERT INTO gadgets (name) VALUES ($1) RETURNING ") + kColumns, name);
                    return Domain::Gadget::from_row(r[0]);
                });
            },
            detail::throw_on<DuplicateGadget>("23505"));
    }

    void remove(const std::string& id) {
        Database::get().execute_write([&](auto& txn) {
            auto r = txn.exec_params("DELETE FROM gadgets WHERE id = $1 RETURNING id", id);
            if (r.empty())
                throw GadgetNotFound{};
            return 0;
        });
    }
};

}  // namespace Repositories
