/**
 * @file test_gadget_domain.cpp
 * @brief Unit tests for Domain::Gadget (serialization). No infra — runs in
 *        the unit bucket. Generated by scripts/new-resource.sh.
 */

#include <gtest/gtest.h>

#include <nlohmann/json.hpp>

#include "domain/Gadget.hpp"

using json = nlohmann::json;

TEST(GadgetDomain, ToJsonSerializesEveryField) {
    Domain::Gadget e;
    e.id = "11111111-1111-1111-1111-111111111111";
    e.name = "example";
    e.created_at = "2026-01-01T00:00:00Z";

    json j = e;  // ADL to_json

    EXPECT_EQ(j["id"], e.id);
    EXPECT_EQ(j["name"], e.name);
    EXPECT_EQ(j["created_at"], e.created_at);
    // NEVER serialize secrets in to_json. If you add a sensitive field, assert
    // it is ABSENT here (see tests/unit/test_domain_serialization.cpp).
}
